package Battleground;
import Superhero.Superhero;
import Heroes.Superman;
import Heroes.Batman;
import Heroes.Hulk;
import Heroes.Ironman;
public class Battleground {
    public Main.Superhero opponent1;
    public Main.Superhero opponent2;
    public void battle(Main.Superhero opponent1 , Main.Superhero opponent2){
        int counterOfRounds = 1;
        while (!opponent1.isDeath() && !opponent2.isDeath()){
            System.out.println("\t\t\t\tRound " + counterOfRounds );
            opponent1.attack(opponent2);
            opponent2.attack(opponent1);
            counterOfRounds++;
            if (opponent1.isDeath()){
                System.out.println(opponent1.getName() + " is dead\n\nThe winner is " +
                        opponent2.getName());
            }
            if (opponent2.isDeath()){
                System.out.println(opponent2.getName() + " is dead\n\nThe winner is " +
                        opponent1.getName());
            }
        }
    }
    public void choiceOfFighters(int fighter1 , int fighter2){
        switch (fighter1){
            case 1 : this.opponent1 = new Superman(120, 10, 40 ,10000, 20);
                break;
            case 2 : this.opponent1 = new Main.Batman(90, 5,30 ,3, 6);
                break;
            case 3 : this.opponent1 = new Hulk(120, 20,40 ,10000, 30);
                break;
            case 4 : this.opponent1 = new Ironman(90, 3, 35,4, 8);
                break;
            default : System.out.println("You enter wrong number");
                break;
        }
        switch (fighter2 ){
            case 1 : this.opponent2 = new Superman(120, 10, 40,10000, 20);
                break;
            case 2 : this.opponent2 = new Main.Batman(90, 5,30, 3, 6);
                break;
            case 3 : this.opponent2 = new Hulk(120, 20, 40,10000, 30);
                break;
            case 4 : this.opponent2 = new Ironman(90, 3,35, 4, 8);
                break;
            default : System.out.println("You enter wrong number");
                break;
        }
    }
    public void cards(int choice) {
        if (choice == 1){
            System.out.println("\t\t\t\tSuperman\t\tBatman\t\t\tHulk\t\t\tIron man\n" +
                            "---------------------------------------------------------------------
                                    -------\n" +
                    "health:\t\t\t120\t\t\t\t90\t\t\t\t120\t\t\t\t90\t\t\t\t\t//xp\n" +
                            "damage:\t\t\t10-40\t\t\t5-30\t\t\t20-40\t\t\t3-35\t\t\t\t//diapason
                    of damage by one attack\n" +
                    "armor:\t\t\t-\t\t\t\t1 in 3\t\t\t-\t\t\t\t1 in 4\t\t\t\t//probability
                    to be protected from damage by armor\n" +
            "regeneration:\t20\t\t\t\t6\t\t\t\t30\t\t\t\t8\t\t\t\t\t//max amount
            of health can be regenerated by hero\n" +
            "---------------------------------------------------------------------
                    -------\n");
        }
    }
}